### ISSUE TITLE
Clarify licensing terms

### ISSUE THREAD

**Issue by esseks** [bduncavage/PullToRefresharp#19]
Your project is currently released out of any licensing scheme. This leaves a lot of gray areas in the usage of your code, especially wrt closed source projects and liability waiver (i.e. "use this code at your own risk").

You are stating in the README that your code is open source, but that's not enough. You should really provide a license, just choose the best fit among the "standard" ones, e.g. MIT, Apache 2.0 or GPLv2/3.

**Comment by bduncavage** [comment]
Thanks for pointing that out. I've added the explicit MIT license to this project in the README.
